version: "3"
services:
  db:
    container_name: "mssql-01"
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "xoho@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  mongo:
    container_name: "mongo-01"
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    container_name: "mongo-express-01"
    image: mongo-express
    ports:
    - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
